version: 2
updates:
  # Root package.json
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "zod"

  # Mobile app
  - package-ecosystem: "npm"
    directory: "/Mobile"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "react-native"
      - dependency-name: "react-native-gesture-handler"
      - dependency-name: "react-native-screens"
      - dependency-name: "react-native-worklets"

  # Website
  - package-ecosystem: "npm"
    directory: "/Website"
    schedule:
      interval: "weekly"

  # form-schemas
  - package-ecosystem: "npm"
    directory: "/Shared/form-schemas"
    schedule:
      interval: "weekly"

  # types
  - package-ecosystem: "npm"
    directory: "/Shared/types"
    schedule:
      interval: "weekly"

  # hooks
  - package-ecosystem: "npm"
    directory: "/Shared/hooks"
    schedule:
      interval: "weekly"

  # .NET backend
  - package-ecosystem: "nuget"
    directory: "/WebServer/"
    schedule:
      interval: "weekly"
      day: "monday"
