// <auto-generated />
using System;
using Hobbyist.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hobbyist.Api.Migrations
{
    [DbContext(typeof(HobbyistDbContext))]
    partial class HobbyistDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hobbyist.Api.Data.Entities.HobbyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2f7a4f09-c6b7-42dd-a646-b6f36e25b0c1"),
                            Name = "trading cards"
                        },
                        new
                        {
                            Id = new Guid("8d9458bb-2303-442b-a4df-08f6bf6bf4f2"),
                            Name = "vinyl records"
                        },
                        new
                        {
                            Id = new Guid("1d3b89e5-3fc0-4f6c-bded-53afe9946f0a"),
                            Name = "coins"
                        },
                        new
                        {
                            Id = new Guid("f9c8f2a6-c5cf-42bb-9f72-701a8e39b539"),
                            Name = "stamps"
                        },
                        new
                        {
                            Id = new Guid("a90d8e15-dad2-4894-a9ca-b5e3f3f42c57"),
                            Name = "comics"
                        },
                        new
                        {
                            Id = new Guid("6e662a47-fde0-4546-ac66-bf0ddfdf1a27"),
                            Name = "figures"
                        },
                        new
                        {
                            Id = new Guid("ea76d9f2-08a7-4b38-83ef-e4f0d8b734ab"),
                            Name = "ceramics"
                        },
                        new
                        {
                            Id = new Guid("5e4a94f2-a021-48ab-b2c0-a79a6d6ff43d"),
                            Name = "art prints"
                        },
                        new
                        {
                            Id = new Guid("f56b64ac-f453-4f4f-8730-8d1b7e3fda08"),
                            Name = "vintage toys"
                        },
                        new
                        {
                            Id = new Guid("6fccf7e8-1615-422f-a654-210779464fc8"),
                            Name = "watches"
                        },
                        new
                        {
                            Id = new Guid("b197c6aa-2c48-4a03-b8a5-c190d900f8e5"),
                            Name = "jewellery"
                        },
                        new
                        {
                            Id = new Guid("9b6f7d4e-687a-4f8a-85cc-682ec8905196"),
                            Name = "books"
                        },
                        new
                        {
                            Id = new Guid("f492c588-a045-4466-8f26-0fd9bb90989e"),
                            Name = "cameras"
                        },
                        new
                        {
                            Id = new Guid("6eadbe6c-20ba-4f9a-9196-6ae0ac88d7bb"),
                            Name = "video games"
                        },
                        new
                        {
                            Id = new Guid("859c18b6-ef67-4f31-a84d-686f0adf4512"),
                            Name = "rare plants"
                        },
                        new
                        {
                            Id = new Guid("5d22fd82-f357-45dc-be7b-1a22ff13d9d0"),
                            Name = "minerals"
                        },
                        new
                        {
                            Id = new Guid("19da3f2b-736f-436b-84de-7d930c3f56fb"),
                            Name = "sneakers"
                        },
                        new
                        {
                            Id = new Guid("3fcd0f37-9401-43fb-b9ad-f5734b396497"),
                            Name = "antique maps"
                        });
                });

            modelBuilder.Entity("Hobbyist.Api.Data.Entities.PostEntities.PostEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("AvailableForTrade")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Hobby")
                        .HasColumnType("text");

                    b.Property<int>("Likes")
                        .HasColumnType("integer");

                    b.Property<string>("LookingFor")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Hobbyist.Api.Data.Entities.PostEntities.PostMediaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PostId", "Position");

                    b.ToTable("PostMedia");
                });

            modelBuilder.Entity("Hobbyist.Api.Data.Entities.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Hobbyist.Api.Data.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UserHobbies", b =>
                {
                    b.Property<Guid>("HobbiesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("HobbiesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("UserHobbies");
                });

            modelBuilder.Entity("Hobbyist.Api.Data.Entities.PostEntities.PostEntity", b =>
                {
                    b.HasOne("Hobbyist.Api.Data.Entities.UserEntity", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hobbyist.Api.Data.Entities.PostEntities.PostMediaEntity", b =>
                {
                    b.HasOne("Hobbyist.Api.Data.Entities.PostEntities.PostEntity", "Post")
                        .WithMany("Media")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Hobbyist.Api.Data.Entities.RefreshTokenEntity", b =>
                {
                    b.HasOne("Hobbyist.Api.Data.Entities.UserEntity", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserHobbies", b =>
                {
                    b.HasOne("Hobbyist.Api.Data.Entities.HobbyEntity", null)
                        .WithMany()
                        .HasForeignKey("HobbiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hobbyist.Api.Data.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hobbyist.Api.Data.Entities.PostEntities.PostEntity", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("Hobbyist.Api.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
