/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppTradeRouteImport } from './routes/_app/trade'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppMessagesRouteImport } from './routes/_app/messages'
import { Route as AppEventsRouteImport } from './routes/_app/events'
import { Route as AppCreateRouteImport } from './routes/_app/create'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppProfileIndexRouteImport } from './routes/_app/profile/index'
import { Route as AppSettingsProfileRouteImport } from './routes/_app/settings/profile'
import { Route as AppSettingsAccountRouteImport } from './routes/_app/settings/account'
import { Route as AppProfileUsernameIndexRouteImport } from './routes/_app/profile/$username/index'
import { Route as AppProfileUsernamePostIdRouteImport } from './routes/_app/profile/$username/$postId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppTradeRoute = AppTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppProfileUsernameIndexRoute = AppProfileUsernameIndexRouteImport.update({
  id: '/profile/$username/',
  path: '/profile/$username/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileUsernamePostIdRoute =
  AppProfileUsernamePostIdRouteImport.update({
    id: '/profile/$username/$postId',
    path: '/profile/$username/$postId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/create': typeof AppCreateRoute
  '/events': typeof AppEventsRoute
  '/messages': typeof AppMessagesRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/trade': typeof AppTradeRoute
  '/login': typeof AuthLoginRoute
  '/sign-up': typeof AuthSignUpRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/profile/': typeof AppProfileIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/profile/$username/$postId': typeof AppProfileUsernamePostIdRoute
  '/profile/$username/': typeof AppProfileUsernameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/create': typeof AppCreateRoute
  '/events': typeof AppEventsRoute
  '/messages': typeof AppMessagesRoute
  '/search': typeof AppSearchRoute
  '/trade': typeof AppTradeRoute
  '/login': typeof AuthLoginRoute
  '/sign-up': typeof AuthSignUpRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/profile': typeof AppProfileIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/profile/$username/$postId': typeof AppProfileUsernamePostIdRoute
  '/profile/$username': typeof AppProfileUsernameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/create': typeof AppCreateRoute
  '/_app/events': typeof AppEventsRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/trade': typeof AppTradeRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_app/': typeof AppIndexRoute
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/profile': typeof AppSettingsProfileRoute
  '/_app/profile/': typeof AppProfileIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/profile/$username/$postId': typeof AppProfileUsernamePostIdRoute
  '/_app/profile/$username/': typeof AppProfileUsernameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/events'
    | '/messages'
    | '/search'
    | '/settings'
    | '/trade'
    | '/login'
    | '/sign-up'
    | '/settings/account'
    | '/settings/profile'
    | '/profile/'
    | '/settings/'
    | '/profile/$username/$postId'
    | '/profile/$username/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/events'
    | '/messages'
    | '/search'
    | '/trade'
    | '/login'
    | '/sign-up'
    | '/settings/account'
    | '/settings/profile'
    | '/profile'
    | '/settings'
    | '/profile/$username/$postId'
    | '/profile/$username'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/create'
    | '/_app/events'
    | '/_app/messages'
    | '/_app/search'
    | '/_app/settings'
    | '/_app/trade'
    | '/_auth/login'
    | '/_auth/sign-up'
    | '/_app/'
    | '/_app/settings/account'
    | '/_app/settings/profile'
    | '/_app/profile/'
    | '/_app/settings/'
    | '/_app/profile/$username/$postId'
    | '/_app/profile/$username/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/trade': {
      id: '/_app/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof AppTradeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create': {
      id: '/_app/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/profile/$username/': {
      id: '/_app/profile/$username/'
      path: '/profile/$username'
      fullPath: '/profile/$username/'
      preLoaderRoute: typeof AppProfileUsernameIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/$username/$postId': {
      id: '/_app/profile/$username/$postId'
      path: '/profile/$username/$postId'
      fullPath: '/profile/$username/$postId'
      preLoaderRoute: typeof AppProfileUsernamePostIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppCreateRoute: typeof AppCreateRoute
  AppEventsRoute: typeof AppEventsRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppTradeRoute: typeof AppTradeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppProfileUsernamePostIdRoute: typeof AppProfileUsernamePostIdRoute
  AppProfileUsernameIndexRoute: typeof AppProfileUsernameIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCreateRoute: AppCreateRoute,
  AppEventsRoute: AppEventsRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppTradeRoute: AppTradeRoute,
  AppIndexRoute: AppIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppProfileUsernamePostIdRoute: AppProfileUsernamePostIdRoute,
  AppProfileUsernameIndexRoute: AppProfileUsernameIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
