/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/feature-flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FeatureFlagsResponse"];
                        "application/json": components["schemas"]["FeatureFlagsResponse"];
                        "text/json": components["schemas"]["FeatureFlagsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Posts/init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Starts a post: validates the manifest and returns a pre-signed upload URL per file. The post
         *     is created as a Draft; the client uploads the bytes directly to storage, then calls finalize
         *     (with `publish: true` to go live, or `false` to keep it a draft).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InitPostRequest"];
                    "text/json": components["schemas"]["InitPostRequest"];
                    "application/*+json": components["schemas"]["InitPostRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["InitPostResponse"];
                        "application/json": components["schemas"]["InitPostResponse"];
                        "text/json": components["schemas"]["InitPostResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Posts/{slug}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verifies that a post's uploads have landed in storage. Publishes it when
         *     bool FinalizeRequest.Publish is true and all files are present; otherwise leaves it
         *     a draft. Returns the positions still missing if any are incomplete.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FinalizeRequest"];
                    "text/json": components["schemas"]["FinalizeRequest"];
                    "application/*+json": components["schemas"]["FinalizeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FinalizeResponse"];
                        "application/json": components["schemas"]["FinalizeResponse"];
                        "text/json": components["schemas"]["FinalizeResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Posts/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Discards a post and its uploaded media (drafts or in-progress posts). Performs a
         *     best-effort bulk deletion of the associated storage objects before removing the record.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth-session/get-user-details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetUserResponse"];
                        "application/json": components["schemas"]["GetUserResponse"];
                        "text/json": components["schemas"]["GetUserResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth-session/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": null | components["schemas"]["RefreshTokenRequest"];
                    "text/json": null | components["schemas"]["RefreshTokenRequest"];
                    "application/*+json": null | components["schemas"]["RefreshTokenRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResult"];
                        "application/json": components["schemas"]["AuthResult"];
                        "text/json": components["schemas"]["AuthResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Login/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StartLoginRequest"];
                    "text/json": components["schemas"]["StartLoginRequest"];
                    "application/*+json": components["schemas"]["StartLoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StartLoginResponse"];
                        "application/json": components["schemas"]["StartLoginResponse"];
                        "text/json": components["schemas"]["StartLoginResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Login/resend-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResendOtpRequest"];
                    "text/json": components["schemas"]["ResendOtpRequest"];
                    "application/*+json": components["schemas"]["ResendOtpRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OtpResponse"];
                        "application/json": components["schemas"]["OtpResponse"];
                        "text/json": components["schemas"]["OtpResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Login/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CompleteLoginRequest"];
                    "text/json": components["schemas"]["CompleteLoginRequest"];
                    "application/*+json": components["schemas"]["CompleteLoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResult"];
                        "application/json": components["schemas"]["AuthResult"];
                        "text/json": components["schemas"]["AuthResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sign-up/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StartSignUpRequest"];
                    "text/json": components["schemas"]["StartSignUpRequest"];
                    "application/*+json": components["schemas"]["StartSignUpRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OtpResponse"];
                        "application/json": components["schemas"]["OtpResponse"];
                        "text/json": components["schemas"]["OtpResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sign-up/verify-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VerifyOtpRequest"];
                    "text/json": components["schemas"]["VerifyOtpRequest"];
                    "application/*+json": components["schemas"]["VerifyOtpRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["VerifyOtpResponse"];
                        "application/json": components["schemas"]["VerifyOtpResponse"];
                        "text/json": components["schemas"]["VerifyOtpResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sign-up/resend-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResendOtpRequest"];
                    "text/json": components["schemas"]["ResendOtpRequest"];
                    "application/*+json": components["schemas"]["ResendOtpRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OtpResponse"];
                        "application/json": components["schemas"]["OtpResponse"];
                        "text/json": components["schemas"]["OtpResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sign-up/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CompleteSignUpRequest"];
                    "text/json": components["schemas"]["CompleteSignUpRequest"];
                    "application/*+json": components["schemas"]["CompleteSignUpRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResult"];
                        "application/json": components["schemas"]["AuthResult"];
                        "text/json": components["schemas"]["AuthResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthResult: {
            accessToken: string;
            refreshToken: string;
            /** Format: date-time */
            accessTokenExpiresAt: string;
            /** Format: date-time */
            refreshTokenExpiresAt: string;
        };
        /** @description Request to complete login using received OTP code. */
        CompleteLoginRequest: {
            identifier: string;
            otp: string;
        };
        /** @description Contains complete user profile information including personal details and password. */
        CompleteSignUpRequest: {
            username: string;
            email: string;
            password: string;
            firstname: string;
            lastname: string;
            dateOfBirth: string;
            interests: string[];
        };
        /** @description Response containing the enabled/disabled state of every feature flag. */
        FeatureFlagsResponse: {
            flags: {
                [key: string]: boolean;
            };
        };
        /** @description Request body for finalize: whether to publish the post or leave it a draft. */
        FinalizeRequest: {
            /** @description True to publish once all media is verified; false to verify and keep it a draft. */
            publish: boolean;
        };
        /** @description Outcome of finalizing a post. */
        FinalizeResponse: {
            /** @description True when every file was verified and a publish was requested, so the post is now live. */
            published: boolean;
            /**
             * @description Positions whose object was not yet found in storage. Empty means every file landed
             *         (the post is published when publish was requested, or a verified draft otherwise). Non-empty
             *         means the upload is incomplete: the web client discards and recreates; a future mobile client
             *         can re-upload just these positions.
             */
            pendingPositions: (number | string)[];
        };
        /** @description Response containing current user authentication status and user data if authenticated. */
        GetUserResponse: {
            isAuthenticated: boolean;
            user?: null | components["schemas"]["UserDto"];
        };
        /**
         * @description Request to start a post. Metadata is optional so the user can save at any point; only the media
         *     manifest is required. The server always creates the post in the Draft state and returns a
         *     pre-signed upload URL per manifest item — whether it ends up published is decided at finalize,
         *     so publish and draft share this one request shape.
         */
        InitPostRequest: {
            hobby?: null | string;
            title?: null | string;
            description?: null | string;
            availableForTrade?: boolean;
            lookingFor?: null | string;
            media: components["schemas"]["MediaManifestItem"][];
        };
        /** @description Returned from init: the new post slug and the per-file upload targets. */
        InitPostResponse: {
            slug: string;
            uploads: components["schemas"]["PresignedUpload"][];
        };
        /** @description One entry in the upload manifest — describes a file the client intends to upload. */
        MediaManifestItem: {
            /**
             * Format: int32
             * @description Display order within the post (1-based). Also the handle the client uses to match
             *         a returned upload URL back to its file.
             */
            position: number | string;
            /** @description Original file name; the server derives the stored extension from this. */
            fileName: string;
            contentType: string;
            /** Format: int64 */
            byteSize: number | string;
        };
        /** @description Response containing OTP expiration timestamp. */
        OtpResponse: {
            /** Format: date-time */
            otpExpiresAt: string;
        };
        /** @description A single pre-signed upload target returned to the client, paired with its manifest position. */
        PresignedUpload: {
            /** Format: int32 */
            position: number | string;
            url: string;
            /** @description Headers the client must send on the PUT for the signature to match (e.g. Content-Type). */
            requiredHeaders: {
                [key: string]: string;
            };
            /** Format: date-time */
            expiresAt: string;
        };
        /** @description Request containing refresh token for mobile token refresh. */
        RefreshTokenRequest: {
            refreshToken: string;
        };
        /** @description Request to resend OTP code to specified email address. */
        ResendOtpRequest: {
            email: string;
        };
        /** @description Credentials for initiating the login process. */
        StartLoginRequest: {
            identifier: string;
            password: string;
        };
        /** @description Response after initiating login, containing OTP expiration and destination email. */
        StartLoginResponse: {
            otpExpiresAt: string;
            email: string;
        };
        /** @description Contains username and email to initiate the sign-up process. */
        StartSignUpRequest: {
            username: string;
            email: string;
        };
        /** @description Defines a transferable user. Stores non-sensitive information like the username, and name of user. */
        UserDto: {
            id: string;
            username: string;
            email: string;
            firstname: string;
            lastname: string;
        };
        /** @description Request to verify email address using OTP code during sign-up. */
        VerifyOtpRequest: {
            email: string;
            otp: string;
        };
        VerifyOtpResponse: {
            popularInterests: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
