/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/feature-flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FeatureFlagsResponse"];
                        "application/json": components["schemas"]["FeatureFlagsResponse"];
                        "text/json": components["schemas"]["FeatureFlagsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Posts/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creates and publishes a post in one shot (mobile optimistic-post flow). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        Hobby?: string;
                        Title?: string;
                        Description?: string;
                        AvailableForTrade?: boolean;
                        LookingFor?: string;
                        Media?: components["schemas"]["IFormFile"][];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreatePostResponse"];
                        "application/json": components["schemas"]["CreatePostResponse"];
                        "text/json": components["schemas"]["CreatePostResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Posts/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Saves a complete draft — all form fields and media in one request.
         *     The draft sits on the server until the user chooses to publish it.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        Hobby?: string;
                        Title?: string;
                        Description?: string;
                        AvailableForTrade?: boolean;
                        LookingFor?: string;
                        Media?: components["schemas"]["IFormFile"][];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateDraftResponse"];
                        "application/json": components["schemas"]["CreateDraftResponse"];
                        "text/json": components["schemas"]["CreateDraftResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Posts/{slug}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publishes a saved draft. All required data is already on the draft;
         *     no additional fields are needed from the caller.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreatePostResponse"];
                        "application/json": components["schemas"]["CreatePostResponse"];
                        "text/json": components["schemas"]["CreatePostResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Posts/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Discards a draft post. Deletes the database record and performs a
         *     best-effort bulk deletion of all associated S3 objects.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth-session/get-user-details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetUserResponse"];
                        "application/json": components["schemas"]["GetUserResponse"];
                        "text/json": components["schemas"]["GetUserResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth-session/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": null | components["schemas"]["RefreshTokenRequest"];
                    "text/json": null | components["schemas"]["RefreshTokenRequest"];
                    "application/*+json": null | components["schemas"]["RefreshTokenRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResult"];
                        "application/json": components["schemas"]["AuthResult"];
                        "text/json": components["schemas"]["AuthResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Login/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StartLoginRequest"];
                    "text/json": components["schemas"]["StartLoginRequest"];
                    "application/*+json": components["schemas"]["StartLoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StartLoginResponse"];
                        "application/json": components["schemas"]["StartLoginResponse"];
                        "text/json": components["schemas"]["StartLoginResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Login/resend-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResendOtpRequest"];
                    "text/json": components["schemas"]["ResendOtpRequest"];
                    "application/*+json": components["schemas"]["ResendOtpRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OtpResponse"];
                        "application/json": components["schemas"]["OtpResponse"];
                        "text/json": components["schemas"]["OtpResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Login/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CompleteLoginRequest"];
                    "text/json": components["schemas"]["CompleteLoginRequest"];
                    "application/*+json": components["schemas"]["CompleteLoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResult"];
                        "application/json": components["schemas"]["AuthResult"];
                        "text/json": components["schemas"]["AuthResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sign-up/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StartSignUpRequest"];
                    "text/json": components["schemas"]["StartSignUpRequest"];
                    "application/*+json": components["schemas"]["StartSignUpRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OtpResponse"];
                        "application/json": components["schemas"]["OtpResponse"];
                        "text/json": components["schemas"]["OtpResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sign-up/verify-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VerifyOtpRequest"];
                    "text/json": components["schemas"]["VerifyOtpRequest"];
                    "application/*+json": components["schemas"]["VerifyOtpRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["VerifyOtpResponse"];
                        "application/json": components["schemas"]["VerifyOtpResponse"];
                        "text/json": components["schemas"]["VerifyOtpResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sign-up/resend-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResendOtpRequest"];
                    "text/json": components["schemas"]["ResendOtpRequest"];
                    "application/*+json": components["schemas"]["ResendOtpRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OtpResponse"];
                        "application/json": components["schemas"]["OtpResponse"];
                        "text/json": components["schemas"]["OtpResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sign-up/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CompleteSignUpRequest"];
                    "text/json": components["schemas"]["CompleteSignUpRequest"];
                    "application/*+json": components["schemas"]["CompleteSignUpRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResult"];
                        "application/json": components["schemas"]["AuthResult"];
                        "text/json": components["schemas"]["AuthResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthResult: {
            accessToken: string;
            refreshToken: string;
            /** Format: date-time */
            accessTokenExpiresAt: string;
            /** Format: date-time */
            refreshTokenExpiresAt: string;
        };
        /** @description Request to complete login using received OTP code. */
        CompleteLoginRequest: {
            identifier: string;
            otp: string;
        };
        /** @description Contains complete user profile information including personal details and password. */
        CompleteSignUpRequest: {
            username: string;
            email: string;
            password: string;
            firstname: string;
            lastname: string;
            dateOfBirth: string;
            interests: string[];
        };
        /** @description Returned after a draft post is successfully created. */
        CreateDraftResponse: {
            postId: string;
        };
        CreatePostResponse: {
            postId: string;
        };
        /** @description Response containing the enabled/disabled state of every feature flag. */
        FeatureFlagsResponse: {
            flags: {
                [key: string]: boolean;
            };
        };
        /** @description Response containing current user authentication status and user data if authenticated. */
        GetUserResponse: {
            isAuthenticated: boolean;
            user?: null | components["schemas"]["UserDto"];
        };
        /** Format: binary */
        IFormFile: string;
        /** @description Response containing OTP expiration timestamp. */
        OtpResponse: {
            /** Format: date-time */
            otpExpiresAt: string;
        };
        /** @description Request containing refresh token for mobile token refresh. */
        RefreshTokenRequest: {
            refreshToken: string;
        };
        /** @description Request to resend OTP code to specified email address. */
        ResendOtpRequest: {
            email: string;
        };
        /** @description Credentials for initiating the login process. */
        StartLoginRequest: {
            identifier: string;
            password: string;
        };
        /** @description Response after initiating login, containing OTP expiration and destination email. */
        StartLoginResponse: {
            otpExpiresAt: string;
            email: string;
        };
        /** @description Contains username and email to initiate the sign-up process. */
        StartSignUpRequest: {
            username: string;
            email: string;
        };
        /** @description Defines a transferable user. Stores non-sensitive information like the username, and name of user. */
        UserDto: {
            id: string;
            username: string;
            email: string;
            firstname: string;
            lastname: string;
        };
        /** @description Request to verify email address using OTP code during sign-up. */
        VerifyOtpRequest: {
            email: string;
            otp: string;
        };
        VerifyOtpResponse: {
            popularInterests: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
