/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/feature-flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FeatureFlagsResponse"];
                        "application/json": components["schemas"]["FeatureFlagsResponse"];
                        "text/json": components["schemas"]["FeatureFlagsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Posts/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        Hobby?: string;
                        Title?: string;
                        Description?: string;
                        AvailableForTrade?: boolean;
                        LookingFor?: string;
                        Media?: components["schemas"]["IFormFile"][];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreatePostResponse"];
                        "application/json": components["schemas"]["CreatePostResponse"];
                        "text/json": components["schemas"]["CreatePostResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth-session/get-user-details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetUserResponse"];
                        "application/json": components["schemas"]["GetUserResponse"];
                        "text/json": components["schemas"]["GetUserResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth-session/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResult"];
                        "application/json": components["schemas"]["AuthResult"];
                        "text/json": components["schemas"]["AuthResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Login/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StartLoginRequest"];
                    "text/json": components["schemas"]["StartLoginRequest"];
                    "application/*+json": components["schemas"]["StartLoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StartLoginResponse"];
                        "application/json": components["schemas"]["StartLoginResponse"];
                        "text/json": components["schemas"]["StartLoginResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Login/resend-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResendOtpRequest"];
                    "text/json": components["schemas"]["ResendOtpRequest"];
                    "application/*+json": components["schemas"]["ResendOtpRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OtpResponse"];
                        "application/json": components["schemas"]["OtpResponse"];
                        "text/json": components["schemas"]["OtpResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Login/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CompleteLoginRequest"];
                    "text/json": components["schemas"]["CompleteLoginRequest"];
                    "application/*+json": components["schemas"]["CompleteLoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResult"];
                        "application/json": components["schemas"]["AuthResult"];
                        "text/json": components["schemas"]["AuthResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sign-up/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StartSignUpRequest"];
                    "text/json": components["schemas"]["StartSignUpRequest"];
                    "application/*+json": components["schemas"]["StartSignUpRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OtpResponse"];
                        "application/json": components["schemas"]["OtpResponse"];
                        "text/json": components["schemas"]["OtpResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sign-up/verify-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VerifyOtpRequest"];
                    "text/json": components["schemas"]["VerifyOtpRequest"];
                    "application/*+json": components["schemas"]["VerifyOtpRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["VerifyOtpResponse"];
                        "application/json": components["schemas"]["VerifyOtpResponse"];
                        "text/json": components["schemas"]["VerifyOtpResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sign-up/resend-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResendOtpRequest"];
                    "text/json": components["schemas"]["ResendOtpRequest"];
                    "application/*+json": components["schemas"]["ResendOtpRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OtpResponse"];
                        "application/json": components["schemas"]["OtpResponse"];
                        "text/json": components["schemas"]["OtpResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sign-up/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CompleteSignUpRequest"];
                    "text/json": components["schemas"]["CompleteSignUpRequest"];
                    "application/*+json": components["schemas"]["CompleteSignUpRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResult"];
                        "application/json": components["schemas"]["AuthResult"];
                        "text/json": components["schemas"]["AuthResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthResult: {
            accessToken: string;
            refreshToken: string;
            /** Format: date-time */
            accessTokenExpiresAt: string;
            /** Format: date-time */
            refreshTokenExpiresAt: string;
        };
        CompleteLoginRequest: {
            identifier: string;
            otp: string;
        };
        CompleteSignUpRequest: {
            username: string;
            email: string;
            password: string;
            firstname: string;
            lastname: string;
            dateOfBirth: string;
            interests: string[];
        };
        CreatePostResponse: {
            /** Format: uuid */
            postId: string;
        };
        FeatureFlagsResponse: {
            flags: {
                [key: string]: boolean;
            };
        };
        GetUserResponse: {
            isAuthenticated: boolean;
            user?: components["schemas"]["UserDto"];
        };
        /** Format: binary */
        IFormFile: string;
        OtpResponse: {
            /** Format: date-time */
            otpExpiresAt: string;
        };
        ResendOtpRequest: {
            email: string;
        };
        StartLoginRequest: {
            identifier: string;
            password: string;
        };
        StartLoginResponse: {
            otpExpiresAt: string;
            email: string;
        };
        StartSignUpRequest: {
            username: string;
            email: string;
        };
        UserDto: {
            id: string;
            username: string;
            email: string;
            firstname: string;
            lastname: string;
        } | null;
        VerifyOtpRequest: {
            email: string;
            otp: string;
        };
        VerifyOtpResponse: {
            popularInterests: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
