name: .NET
permissions:
    contents: read

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:18
                env:
                    POSTGRES_PASSWORD: Password123.
                    POSTGRES_USER: postgres
                    POSTGRES_DB: postgres
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432

        steps:
            - uses: actions/checkout@v7
            - name: Setup .NET
              uses: actions/setup-dotnet@v5
              with:
                  dotnet-version: 10.0.x
            - name: Restore dependencies
              run: dotnet restore
              working-directory: WebServer/
            - name: Build
              run: dotnet build --no-restore --warnaserror
              working-directory: WebServer/
            - name: Test
              run: dotnet test --no-build --verbosity normal
              working-directory: WebServer/
              env:
                  TEST_DB_CONNECTION_STRING: Host=localhost;Port=5432;Username=postgres;Password=Password123.;Database=test_db
